spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: aa
          uri: lb://aa
          predicates:
            - Path=/api/aa/**
          filters:
            - RewritePath=/api/aa(?<segment>/?.*), $\{segment}


server:
  port: 8080

eureka:
  instance:
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      startup: ${random.int}

  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}