version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - audiostream

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - audiostream
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  api-gateway:
    container_name: audiostream-api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: audiostream-api-gateway:latest
    networks:
      - audiostream
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      KEYCLOAK_URI: http://keycloak:8080
      KEYCLOAK_EXTERNAL_URI: http://localhost:8763
      KEYCLOAK_CLIENT_ID: audiostream-service
      KEYCLOAK_CLIENT_SECRET: cfd9ab89-a6fe-48ea-ac8a-66cff1ff998b
    ports:
      - 8080:8080
    depends_on:
      - keycloak

  eureka-server:
    container_name: audiostream-eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: audiostream-eureka-server:latest
    networks:
      - audiostream
    ports:
      - 8761:8761

  keycloak-postgres:
    container_name: keycloak-auth-db
    image: postgres
    networks:
      - audiostream-auth
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    container_name: keycloak-auth-server
    image: quay.io/keycloak/keycloak:latest
    networks:
      - audiostream
      - audiostream-auth
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_FRONTEND_URL: http://localhost:8763/auth
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
    ports:
      - 8763:8080
    depends_on:
      - keycloak-postgres

networks:
  audiostream:
    external: true

  audiostream-auth:
    name: audiostream-auth
    driver: bridge