version: '3'

services:
  api-gateway:
    container_name: audiostream-api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: audiostream-api-gateway:latest
    networks:
      - audiostream
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
    ports:
      - 8080:8080

  eureka-server:
    container_name: audiostream-eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: audiostream-eureka-server:latest
    networks:
      - audiostream
    ports:
      - 8761:8761

  keycloak-postgres:
    container_name: keycloak-auth-db
    image: postgres
    networks:
      - audiostream-auth
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    container_name: keycloak-auth-server
    image: quay.io/keycloak/keycloak:latest
    networks:
      - audiostream
      - audiostream-auth
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8763:8080
    depends_on:
      - keycloak-postgres

networks:
  audiostream:
    external: true

  audiostream-auth:
    name: audiostream-auth
    driver: bridge