version: '3'

services:
  audiostream-streaming-db:
    container_name: audiostream-streaming-db
    image: postgres
    networks:
      - audiostream-streaming
    environment:
      POSTGRES_DB: audiostream
      POSTGRES_USER: streaming
      POSTGRES_PASSWORD: streaming

  streaming-redis:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - audiostream
      - audiostream-streaming

  streaming-api:
    container_name: audiostream-streaming-api
    build:
      context: .
      dockerfile: Dockerfile
    image: audiostream-streaming-api:latest
    networks:
      - audiostream
      - audiostream-streaming
    environment:
      DB_ADDR: jdbc:postgresql://audiostream-streaming-db:5432/audiostream
      DB_USER: streaming
      DB_PASSWORD: streaming
      KAFKA_URI: kafka:29092
      EUREKA_URI: http://eureka-server:8761/eureka
      KEYCLOAK_URI: http://keycloak:8080
      SPRING_REDIS_HOST: streaming-redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - audiostream-streaming-db
      - streaming-redis

networks:
  audiostream:
    external: true

  audiostream-streaming:
    name: audiostream-streaming
    driver: bridge