version: '3'

services:
  audiostream-recommendation-db:
    container_name: audiostream-recommendation-db
    image: mongo
    restart: always
    networks:
      - audiostream-recommendation-engine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  recommendation-engine:
    container_name: audiostream-recommendation-engine
    build:
      context: .
      dockerfile: Dockerfile
    image: audiostream-recommendation-engine:latest
    networks:
      - audiostream
      - audiostream-recommendation-engine
    environment:
      DB_ADDR: mongodb://audiostream-recommendation-db:27017/audiostream
      DB_USER: root
      DB_PASSWORD: example
      EUREKA_URI: http://eureka-server:8761/eureka
    depends_on:
      - audiostream-recommendation-db

networks:
  audiostream:
    external: true

  audiostream-recommendation-engine:
    name: audiostream-recommendation-engine
    driver: bridge