version: '3'

services:
  recommendation-engine:
    container_name: audiostream-recommendation-engine
    build:
      context: .
      dockerfile: Dockerfile
    image: audiostream-recommendation-engine:latest
    networks:
      - audiostream
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      KEYCLOAK_URI: http://keycloak:8080

networks:
  audiostream:
    external: true