version: '3'

services:
  keycloak-postgres:
    image: postgres
    networks:
      - audiostream-auth
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    networks:
      - audiostream
      - audiostream-auth
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8763:8080
    depends_on:
      - keycloak-postgres

networks:
  audiostream:
    external: true

  audiostream-auth:
    name: audiostream-auth
    driver: bridge