spring:
  application:
    name: aa
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:postgresql://localhost:5444/aa
    username: gr5
    password: gr5
    driver-class-name: org.postgresql.Driver

  main:
    banner-mode: off

server:
  port: 0

eureka:
  instance:
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      startup: ${random.int}

  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}